// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void emberAfPluginEzspZigbeeProPollTimer0EventHandler(void);
extern EmberEventControl emberAfPluginEzspZigbeeProPollTimer0EventControl;

void emberAfPluginEzspZigbeeProPollTimer1EventHandler(void);
extern EmberEventControl emberAfPluginEzspZigbeeProPollTimer1EventControl;

void emberAfPluginEzspZigbeeProPollTimer2EventHandler(void);
extern EmberEventControl emberAfPluginEzspZigbeeProPollTimer2EventControl;

void emberAfPluginEzspZigbeeProPollTimer3EventHandler(void);
extern EmberEventControl emberAfPluginEzspZigbeeProPollTimer3EventControl;

void emberAfPluginEzspHostTimer0EventHandler(void);
extern EmberEventControl emberAfPluginEzspHostTimer0EventControl;

void emberAfPluginEzspHostTimer1EventHandler(void);
extern EmberEventControl emberAfPluginEzspHostTimer1EventControl;

void emberAfPluginConcentratorSupportLibraryEventHandler(void);
extern EmberEventControl emberAfPluginConcentratorSupportLibraryEventControl;



const EmberEventData emAppEvents[] = {
  {&emberAfPluginEzspZigbeeProPollTimer0EventControl, emberAfPluginEzspZigbeeProPollTimer0EventHandler},
  {&emberAfPluginEzspZigbeeProPollTimer1EventControl, emberAfPluginEzspZigbeeProPollTimer1EventHandler},
  {&emberAfPluginEzspZigbeeProPollTimer2EventControl, emberAfPluginEzspZigbeeProPollTimer2EventHandler},
  {&emberAfPluginEzspZigbeeProPollTimer3EventControl, emberAfPluginEzspZigbeeProPollTimer3EventHandler},
  {&emberAfPluginEzspHostTimer0EventControl, emberAfPluginEzspHostTimer0EventHandler},
  {&emberAfPluginEzspHostTimer1EventControl, emberAfPluginEzspHostTimer1EventHandler},
  {&emberAfPluginConcentratorSupportLibraryEventControl, emberAfPluginConcentratorSupportLibraryEventHandler},
  {NULL, NULL}
};
