// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __NCP_BOOKKEEPING_H__
#define __NCP_BOOKKEEPING_H__


void emberAfEzspGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);

void emberAfEzspGetExtendedValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);

void emberAfEzspSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);

void emberAfEzspGetPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);

void emberAfEzspSetPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);

void emberAfEzspGetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);

void emberAfEzspSetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);

void emberAfPluginEzspModifyMemoryAllocationCallback(void);

void emberAfPluginEzspPermitHostToNcpFrameCallback(bool* permit);

void emberAfInit(void);

void emberAfTick(void);

#endif // __NCP_BOOKKEEPING_H__
